<?php
use Magento\Framework\App\Action\Action;
switch ($type = $block->getType()) {
        case 'cart-products-top':
        $maxProductsDisplay = $block->getMaxProductsDisplay();
        $items = $block->getProductColletion();
        $image = 'category_page_grid';
        $limit = 0;
        $shuffle = 0;
        $type = 'related';
        $exist = count($block->getProductColletion());
        $class = $type;
        $numberOfRows = $block->getNumberOfRows();
        $showAddTo = $block->getDisplayCartButton();
        $blockLayout = $block->getBlockLayout();

        break;
        
        case 'cart-products-bottom':
        $maxProductsDisplay = $block->getMaxProductsDisplay();
        $items = $block->getProductColletion();
        $image = 'category_page_grid';
        $limit = 0;
        $shuffle = 0;
        $type = 'related';
        $exist = count($block->getProductColletion());
        $class = $type;
        $showAddTo = $block->getDisplayCartButton();
        $numberOfRows = $block->getNumberOfRows();
        $blockLayout = $block->getBlockLayout();

        break;
        
        case 'crosssell':
        $maxProductsDisplay = $block->getMaxProductsDisplay();
        $items = $block->getProductColletion();
        $image = 'category_page_grid';
        $limit = 0;
        $shuffle = 0;
        $type = 'crosssell';
        $exist = count($block->getProductColletion());
        $class = $type;
        $showAddTo = $block->getDisplayCartButton();
        $numberOfRows = $block->getNumberOfRows();
        $blockLayout = $block->getBlockLayout();

        break;
        
        case 'cart-products-before':
        $maxProductsDisplay = $block->getMaxProductsDisplay();
        $items = $block->getProductColletion();
        $image = 'category_page_grid';
        $limit = 0;
        $shuffle = 0;
        $type = 'crosssell';
        $exist = count($block->getProductColletion());
        $class = $type;
        $showAddTo = $block->getDisplayCartButton();
        $numberOfRows = $block->getNumberOfRows();
        $blockLayout = $block->getBlockLayout();

        break;
        
        case 'cart-products-after':
        
        $maxProductsDisplay = $block->getMaxProductsDisplay();
        $items = $block->getProductColletion();
        $image = 'category_page_grid';
        $limit = 0;
        $shuffle = 0;
        $type = 'crosssell';
        $exist = count($block->getProductColletion());
        $class = $type;
        $showAddTo = $block->getDisplayCartButton();
        $numberOfRows = $block->getNumberOfRows();
        $blockLayout = $block->getBlockLayout();
        break;
        
        case 'order-success-page':
        $maxProductsDisplay = $block->getMaxProductsDisplay();
        $items = $block->getProductColletion();
        $image = 'category_page_grid';
        $limit = 0;
        $shuffle = 0;
        $type = 'related';
        $exist = count($block->getProductColletion());
        $class = $type;
        $showAddTo = $block->getDisplayCartButton();
        $numberOfRows = $block->getNumberOfRows();
        $blockLayout = $block->getBlockLayout();
        break;
        
    case 'other':
        break;
}
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$pos = $block->getPositioned();
$viewMode = 'grid';
$showDescription = false;
?> 
<?php if ($exist): ?>

    <div class="block arp-products-custome-block <?php echo $class; ?> " data-limit="0" data-shuffle="0">
        <div class="block-title title">
            <strong id="block-related-heading" role="heading" aria-level="2">
                <h3><?php /* @escapeNotVerified */ echo $block->getBlockTitle(); ?></h3>
            </strong>
        </div>
        <?php if($block->getCheckboxShow()) { ?>
        <div class="block-actions">
            <?php /* @escapeNotVerified */ echo __('Check items to add to the cart or') ?>
            <button type="button" class="action select" role="select-all"><span><?php /* @escapeNotVerified */ echo __('select all') ?></span></button>
        </div>
        <?php } ?>
        <?php if($blockLayout == 1) {
            $layoutclass= "arp-container--grid";
        } else {
            $layoutclass = 'basic-regular ' . $block->getType();
        } ?>
        <div class="arp-container__items <?php echo $layoutclass; ?> " data-aw-arp-columns="<?php echo $numberOfRows; ?>">
            <?php $iterator = 1; ?>
            <?php foreach ($items as $_product) { ?>
                <?php $available = ''; ?>
                <?php if (!$_product->isComposite() && $_product->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_product->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
            <div class="item product product-item arp-container__item">
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php if($block->isShowQuickView()) { ?>
                        <div class="amquickview-hover" style="display: none;">
                            <a class="amquickview-link" id="amquickview-link-<?php /* @escapeNotVerified */ echo $_product->getId() ?>" data-product-id="<?php /* @escapeNotVerified */ echo $_product->getId() ?>" data-rule-id="<?php /* @escapeNotVerified */ echo $block->getRuleId() ?>">
                                <img src="<?php echo $this->getViewFileUrl('Magedelight_Arp::images/len.png'); ?>" class="am-quickview-icon"/> QUICK VIEW
                            </a>
                        </div>
                       <?php } ?>
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php if($showAddTo == 1) { echo $block->getProductDetailsHtml($_product); } ?>

                        <div class="product-item-inner">
                           <?php if($showAddTo == 1) { ?> 
                                <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    data-rule-id="<?php /* @escapeNotVerified */ echo $block->getRuleId() ?>"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php } ?>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php } ?>
        </div>
    </div>

<script type="text/javascript">
require(['jquery','slickslider','popupwindow'], function ($) {
        $(document).ready(function () {
            var sliderId = '<?php echo $block->getType(); ?>';
            var rule_id = '<?php echo $block->getRuleId(); ?>';
            $('.basic-regular.' + sliderId).not('.slick-initialized').slick({
                infinite: false,
                slidesToShow: <?php echo $block->getSlidesToShow(); ?> ,
                slidesToScroll: <?php echo $block->getSlidesToScroll(); ?> ,
                responsive: [
                {
                  breakpoint: 1024,
                  settings: {
                    slidesToShow: 4,
                    slidesToScroll: 1,
                    infinite: true,
                    dots: true
                  }
                },
                {
                  breakpoint: 600,
                  settings: {
                    slidesToShow: 3,
                    slidesToScroll: 1
                  }
                },
                {
                  breakpoint: 480,
                  settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1
                  }
                }
            ]
            });
            $(".amquickview-link").click(function() {
                var product_id = $k(this).attr('data-product-id');
                $.fancybox.open({
                    href : '<?php echo $block->getBaseUrlProd(); ?>advancerelated/catalog/index/id/'+ product_id,
                    type : 'iframe',
                    padding : 5,
                });
            });
            var VisiterIP = 'counter' + rule_id;
            var refreshCounter = 1;
            var OnloadRefresh = localStorage.getItem(VisiterIP);
            if(OnloadRefresh == null) {
                $.ajax({
                    url: '<?php echo $block->getBaseUrlProd(); ?>advancerelated/catalog/pageVisitor/rule_id/' + rule_id,
                    type: "GET"
                });
            }
            localStorage.setItem(VisiterIP, refreshCounter);
            
        })
    });
</script>

<?php endif; ?>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
<?php endif; ?>