<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
$ruleId = $this->getRequest()->getParam('id');
if($ruleId) {
?>
<div style="position: absolute; right: 0; top: 110px;">
    <button type="button" id="product_listing_action">PRODUCTS LISTING</button>
</div>
<div class="productnewgridaction"></div>
<?php  } ?> 
<script>
    require([
        "jquery",
        "accordion",
        "mage/mage",
        'jquery/ui', // Jquery UI Library
    ], function ($) {
//<![CDATA[
        $(document).ready(function () {
            function primaryGrid(){
                $.ajax({
                    showLoader: true,
                    url: baseUrl + 'admin/advancerelated/index/products/id/'+id+'/act/2/form_key/'+key,
                    data: id,
                    type: "POST",
                    success: function (data)
                    {   $('.productnewgridaction').empty();
                        $('.productnewgridaction').prepend('<span type="button" class="admin__collapsible-title" id="product_listing_collapsible_action">\n\
                        CONDITION PRODUCTS</span>\n\
                        ');
                        $('.productnewgridaction').append('<div id="products-list-action">' + data + '</div>');
                        $("#product_listing_collapsible_action").click(function(){
                            $("#products-list-action").slideToggle( "slow" );
                        });
                    },
                    error: function (error)
                    {
                        console.log(error);
                    }
                });
            }
            
            var key = '<?php echo $block->getFormKey(); ?>';
            var id = '<?php echo $this->getRequest()->getParam('id'); ?>';
            var baseUrl = '<?php echo $baseUrl; ?>';
            $('#product_listing_action').click(function () {
               primaryGrid();   
            });
        });
//]]>
    });




</script>