<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Blog
 */
?>
<?php if ($block->getDisplay()): ?>
    <div class="block amblog-search">
        <div class="block-title">
            <strong><span><?php echo $block->getBlockHeader(); ?></span></strong>
        </div>
        <div class="block-content">
            <form id="am_blog_search" action="<?php echo $block->getSearchUrl(); ?>" method="get">
                <div class="input-box">
                    <input type="text" placeholder="<?php echo $block->getBlockHeader(); ?>" class="input-text required-entry placeholder" title="<?php echo $block->getBlockHeader(); ?>" id="search-blog" name="query" value="<?php echo $block->getQuery(); ?>" maxlength="100" />
                </div>
                <button class="button" title="<?php echo __("Search"); ?>" type="submit"><span><span><?php echo __("Search"); ?></span></span></button>
            </form>
        </div>
    </div>
<?php endif; ?>
