<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/** @var \Amasty\Shopby\Block\Navigation\Widget\Tooltip $block */
$filterSetting = $block->getFilterSetting();
$tooltipUrl = $block->getTooltipUrl();

$tooltipTemplate = '<span class="tooltip amshopby-filter-tooltip" title="{content}"><img src="'.$tooltipUrl.'"></span>';
?>
<script type="text/x-magento-init">
        {
            ".am_shopby_filter_items_<?= $block->escapeHtml($filterSetting->getFilterCode())?>": {
                "amShopbyFilterAddTooltip": {
                    "content": <?= json_encode($filterSetting->getTooltip()); ?>,
                    "tooltipTemplate": <?= json_encode($tooltipTemplate); ?>
                }
            }
        }
</script>
