<?php
// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Checkout\Block\Cart\Sidebar
 */
?>
<?php
    $theme = $this->helper('Infortis\Base\Helper\Data');
?>
<div data-block="minicart" class="minicart-wrapper mini-cart dropdown-block" id="minicart">
    <?php /* <a class="action showcart" href="<?php echo $block->getShoppingCartUrl(); ?>" */ ?>
    <div data-skiptarget="#header-cart" class="mini-cart-heading dropdown-heading cover skip-link skip-cart  action showcart" data-bind="scope: 'minicart_content'">
        <span>
            <span class="icon ic ic-cart"></span>
            <span class="counter qty empty"
                  data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
                <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
                <span class="counter-label">
                <!-- ko if: getCartParam('summary_count') -->
                    <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                    <!-- ko i18n: 'items' --><!-- /ko -->
                <!-- /ko -->
                </span>
            </span>
            <span class="label<?php if (!$theme->getCfg('header/cart_label')) echo ' hide'; ?>"><?php /* @escapeNotVerified */ echo __('Cart'); ?></span>
            <span class="caret"></span>
        </span>
    </div>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div id="header-cart" class="mini-cart-content dropdown-content left-hand skip-content skip-content--style block-cart block block-minicart empty"
            data-role="dropdownDialog"
            data-mage-init='{"dropdownDialog":{
                "triggerEvent": "click mouseenter",
                "appendTo": "[data-block=minicart]",
                "triggerTarget": ".showcart",
                "timeout": "200",
                "closeOnMouseLeave": true,
                "closeOnEscape": true,
                "parentClass": "active open",
                "buttons": []}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?php echo $block->getChildHtml('minicart.addons'); ?>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
    <script type="text/javascript">
        //<![CDATA[
        requirejs(['jquery'], function(jQuery) {
            jQuery(function($) {
                // Remove display of minicart dialog which is applied on initialization of dropdownDialog
                $(document).on('dropdowndialogcreate', function(event) {
                    $('#header-cart').css('display', '');
                });
            });
        }); //end: requirejs
        //]]>
    </script>
</div>
