<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Blog
 */
?>
<!-- Twitter Card data -->
<?php if ($block->hasThumbnail()): ?>
    <meta name="twitter:card" content="summary_large_image" />
    <?php else: ?>
    <meta name="twitter:card" content="summary" />
<?php endif; ?>
<?php if ($block->getPublisherTwitter()): ?>
    <meta name="twitter:site" content="<?php echo $block->getPublisherTwitter(); ?>" />
<?php endif; ?>
<meta name="twitter:title" content="<?php echo $block->getPostTitle(); ?>" />
<meta name="twitter:description" content="<?php echo $block->getPostMetaDescription(); ?>" />
<?php if ($block->getAuthorTwitter()): ?>
    <meta name="twitter:creator" content="<?php echo $block->getAuthorTwitter(); ?>" />
<?php endif; ?>
<meta name="twitter:image:src" content="<?php echo $block->getPostUrl(); ?>" />

<!-- Open Graph data -->
<meta property="og:title" content="<?php echo $block->getPostTitle();?>" />
<meta property="og:type" content="article" />
<meta property="og:url" content="<?php echo $block->getPostUrl(); ?>" />
<?php if ($block->hasThumbnail()): ?>
    <meta property="og:image" content="<?php echo $block->getThumbnailSrc(); ?>" />
<?php endif; ?>
<meta property="og:description" content="<?php echo $block->getPostMetaDescription(); ?>" />
<meta property="og:site_name" content="<?php echo $block->getSiteName(); ?>" />
<?php if ($block->getPublisherFacebook()): ?>
    <meta property="article:publisher" content="<?php echo $block->getPublisherFacebook(); ?>" />
<?php endif; ?>
<?php if ($block->getAuthorFacebook()): ?>
    <meta property="article:author" content="<?php echo $block->getAuthorFacebook(); ?>" />
<?php endif; ?>
<meta property="article:published_time" content="<?php echo $block->getPostModifiedDate(); ?>" />
<meta property="article:modified_time" content="<?php echo $block->getPostPublishedDate(); ?>" />
<meta property="article:section" content="<?php echo $block->getPostCategories(); ?>" />
<?php if ($block->getPostTags()->getSize()): ?>
    <?php foreach ($block->getPostTags() as $tag): ?>
        <meta property="article:tag" content="<?php echo $block->escapeHtml($tag->getName()); ?>" />
    <?php endforeach; ?>
<?php endif; ?>

<!-- Google Search Robot -->
<meta itemprop="name" content="<?php echo $block->getPostTitle(); ?>">
<meta itemprop="description" content="<?php echo $block->getPostMetaDescription(); ?>">
<?php if ($block->hasThumbnail()): ?>
    <meta itemprop="image" content="<?php echo $block->getThumbnailSrc(); ?>">
<?php endif; ?>

<script type="text/javascript">
    //<![CDATA[

    $$('html').each(function(element){
        $(element).setAttribute('itemtype','http://schema.org/Blog');
        $(element).setAttribute('itemscope', "");
    });

    //]]>
</script>

