<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php /** @var \Amasty\Shopby\Block\Navigation\State $block */?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)) : ?>
    <div class="filter-current" id="am_shopby_container"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false }}'>
        <strong class="block-subtitle filter-current-subtitle"
                role="heading"
                aria-level="2"
                data-role="title"
                data-count="<?= /* @escapeNotVerified */ count($_filters); ?>">
            <?= $block->escapeHtml(__('Now Shopping by')) ?></strong>
        <ol class="items">
            <?php foreach ($_filters as $_filter) : ?>
                <?php $filterSetting = $this->getFilterSetting($_filter->getFilter());?>
                <li class="item am_shopby_state_container"
                    data-container="<?= /* @escapeNotVerified */ $_filter->getFilter()->getRequestVar() ?>"
                    data-value="<?= $block->escapeHtml($_filter->getValueString(), false) ?>"
                >
                    <span class="filter-label"><?= $block->escapeHtml(__($_filter->getName())); ?></span>
                    <span class="filter-value"><?= $block->viewLabel($_filter);?></span>
                    <?php
                    $clearLinkUrl = $_filter->getClearLinkUrl();
                    $currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " .
                        $block->stripTags($_filter->getLabel());
                    if ($clearLinkUrl) :?>
                        <a class="action previous" href="<?= $_filter->getRemoveUrl() ?>"
                           title="<?= $block->escapeHtml(__('Previous')) ?>">
                            <span><?= $block->escapeHtml(__('Previous')) ?></span>
                        </a>
                        <a class="action remove"
                           title="<?= /* @escapeNotVerified */ $_filter->getFilter()->getClearLinkText() ?>"
                           href="<?= /* @escapeNotVerified */ $clearLinkUrl ?>">
                            <span><?= /* @escapeNotVerified */ $_filter->getFilter()->getClearLinkText() ?></span>
                        </a>
                        <?php
                    else :
                        ?>
                        <a class="action remove" href="<?= /* @escapeNotVerified */ $_filter->getRemoveUrl() ?>"
                           title="<?= $block->escapeHtml(__('Remove')) . " " . $currentFilterName;?>">
                            <span><?= $block->escapeHtml(__('Remove This Item')) ?></span>
                        </a>
                    <?php
                    endif;
                    ?>
                </li>
            <?php endforeach; ?>
        </ol>
        <script type="text/x-magento-init">
{
    "#am_shopby_container": {
        "amShopbyFilterContainer": {
                "collectFilters": <?= /* @escapeNotVerified */ $block->collectFilters(); ?>
           }
    }
}

        </script>
    </div>
<?php endif; ?>
