<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Smtp
 */
?>
<?php /** @var \Magento\Backend\Block\Template $block */ ?>

<?= $block->getChildHtml('button') ?>
<div class="amsmtp-buttoned-input"><?= $block->getData('select_html') ?></div>
<div class="details collapsed" data-role="details">
    <div class="toggle" data-role="toggle"><?=__('Debug info')?></div>
    <div class="error-message" data-role="message"></div>
</div>
